# Generated by Django 6.0.1 on 2026-01-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer34DB',
            fields=[
                ('orderNo', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('placed_time', models.TimeField()),
                ('Email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('Mobile_no', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
